version: '3'

services:
  lb:
    image: haproxy
    ports:
      - "8081:8080"
    networks:
      marketplace:
        ipv4_address: 172.19.0.2 # Assign a static IP address to the lb service
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    restart: always

  paymentservice1:
    image: paymentservice
    environment:
      - APPID=1111
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.19.0.3 # Assign a static IP address to paymentservice1

  paymentservice2:
    image: paymentservice
    environment:
      - APPID=2222
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.19.0.4 # Assign a static IP address to paymentservice2

  paymentservice3:
    image: paymentservice
    environment:
      - APPID=3333
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.19.0.5 # Assign a static IP address to paymentservice3

  paymentservice4:
    image: paymentservice
    environment:
      - APPID=4444
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.19.0.6 # Assign a static IP address to paymentservice4

networks:
  marketplace:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16 # Define a subnet for your custom network named "marketplace"
